### PR TITLE
Fail gracefully when editing pages so other reports are unaffected

### PR DESCRIPTION
**Pull request by MusikAnimal**
Add a bit more logging for easier debugging

Add link to troublshooting tips on the index page

Bug: T286931

### CODE REVIEW

**Review by samwilson — APPROVED** [review]

**Comment by samwilson** [comment]
Looks good to me!

**Comment by samwilson** [comment]
(Sorry about the delay in reviewing.)

**Comment by MusikAnimal** [comment]
No worries and thank you!

**Comment by MusikAnimal** [comment]
I have updated commtech-bot.commtech.eqiad1.wikimedia.cloud accordingly

**Pull request merged**
